#ifndef _ID_H
#define _ID_H

#include <string_view>
#include <utility>

#include "common/src/typedefs.hpp"

enum class Id : Byte
{
	acceptIMs,
	acceptPChats,
	addMyServer,
	addServer,
	agreement,
	agreementStyl,
	awayMsg,
	ban,
	broadcast,
	chat,
	colorChanged,
	createFolder,
	deleteFile,
	denied,
	done,
	echo,
	editFileInfo,
	edServer,
	emote,
	eof,
	failTransfer,
	fileList,
	getCat,
	getFile,
	getInfo,
	getList,
	getProf,
	huh,
	iAgree,
	iconChange,
	iconChanged,
	iDontAgree,
	info,
	init,
	invalidLogin,
	invPrivChat,
	kick,
	killCat,
	killedCat,
	killTransfer,
	listed,
	loggedIn,
	login,
	loginPending,
	moveFile,
	msg,
	msgEmote,
	nameChanged,
	newCat,
	newPrivChat,
	newsList,
	nickChange,
	one,
	pChatLeave,
	pChatUserJoin,
	pChatUserLeave,
	platform,
	postCat,
	privChat,
	privChatAccept,
	privEmote,
	privs,
	putFile,
	refuseIMs,
	refusePChats,
	removed,
	removeServer,
	remServer,
	serverBanner,
	servInfo,
	servMsg,
	setAway,
	setLockNews,
	setSize,
	size,
	theCat,
	theProf,
	three,
	two,
	uid,
	userIn,
	userInfo,
	userList,
	userOut,
	version,
	zero
};

static constexpr std::pair<Id, std::string_view> idMap[] = {
	{ Id::acceptIMs, "acceptims" },
	{ Id::acceptPChats, "acceptpchats" },
	{ Id::addMyServer, "addmyserver" },
	{ Id::addServer, "addserver" },
	{ Id::agreement, "agreement" },
	{ Id::agreementStyl, "agreementstyl" },
	{ Id::awayMsg, "awaymsg" },
	{ Id::ban, "ban" },
	{ Id::broadcast, "broadcast" },
	{ Id::chat, "chat" },
	{ Id::colorChanged, "colorchanged" },
	{ Id::createFolder, "createfolder" },
	{ Id::deleteFile, "deletefile" },
	{ Id::denied, "denied" },
	{ Id::done, "done" },
	{ Id::editFileInfo, "editfileinfo" },
	{ Id::echo, "echo" },
	{ Id::edServer, "edserver" },
	{ Id::emote, "emote" },
	{ Id::eof, "eof" },
	{ Id::failTransfer, "failtransfer" },
	{ Id::fileList, "filelist" },
	{ Id::getCat, "getcat" },
	{ Id::getFile, "getfile" },
	{ Id::getInfo, "getinfo" },
	{ Id::getList, "getlist" },
	{ Id::getProf, "getprof" },
	{ Id::huh, "huh" },
	{ Id::iAgree, "iagree" },
	{ Id::iconChange, "iconchange" },
	{ Id::iconChanged, "iconchanged" },
	{ Id::iDontAgree, "idontagree" },
	{ Id::info, "info" },
	{ Id::init, "init" },
	{ Id::invalidLogin, "invalidlogin" },
	{ Id::invPrivChat, "invprivchat" },
	{ Id::kick, "kick" },
	{ Id::killCat, "killcat" },
	{ Id::killedCat, "killedcat" },
	{ Id::killTransfer, "killtransfer" },
	{ Id::listed, "listed" },
	{ Id::loggedIn, "loggedin" },
	{ Id::login, "login" },
	{ Id::loginPending, "login?" },
	{ Id::moveFile, "movefile" },
	{ Id::msg, "msg" },
	{ Id::msgEmote, "msgemote" },
	{ Id::nameChanged, "namechanged" },
	{ Id::newCat, "newcat" },
	{ Id::newPrivChat, "newprivchat" },
	{ Id::newsList, "newslist" },
	{ Id::nickChange, "nickchange" },
	{ Id::one, "1" },
	{ Id::pChatLeave, "pchatleave" },
	{ Id::pChatUserJoin, "pchatuserjoin" },
	{ Id::pChatUserLeave, "pchatuserleave" },
	{ Id::platform, "platform" },
	{ Id::postCat, "postcat" },
	{ Id::privChat, "privchat" },
	{ Id::privChatAccept, "privchataccept" },
	{ Id::privEmote, "privemote" },
	{ Id::privs, "privs" },
	{ Id::putFile, "putfile" },
	{ Id::refuseIMs, "refuseims" },
	{ Id::refusePChats, "refusepchats" },
	{ Id::removed, "removed" },
	{ Id::removeServer, "removeserver" },
	{ Id::remServer, "remserver" },
	{ Id::serverBanner, "serverbanner" },
	{ Id::servInfo, "servinfo" },
	{ Id::servMsg, "servmsg" },
	{ Id::setAway, "setaway" },
	{ Id::setLockNews, "setlocknews" },
	{ Id::setSize, "setsize" },
	{ Id::size, "size" },
	{ Id::theCat, "thecat" },
	{ Id::theProf, "theprof" },
	{ Id::three, "3" },
	{ Id::two, "2" },
	{ Id::uid, "uid" },
	{ Id::userIn, "userin" },
	{ Id::userInfo, "userinfo" },
	{ Id::userList, "userlist" },
	{ Id::userOut, "userout" },
	{ Id::version, "version" },
	{ Id::zero, "0" }
};

#endif // _ID_H
